name:                http-server
version:             0.1.0.0
github:              "sstreef/research-project"
license:             OtherLicense
author:              "Sam Streef"
maintainer:          "s.l.streef@student.tudelft.nl"
copyright:           "2022 Sam Streef"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sstreef/research-project/tree/main/code/http-server>

dependencies:
- base >= 4.7 && < 5
- network

# Misc
- bytestring
- containers

# Testing
- test-framework >= 0.8 && < 0.9
- test-framework-quickcheck2 >= 0.3 && < 0.4
- QuickCheck >= 2.13 && < 2.15

library:
  source-dirs: src

executables:
  http-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-server

tests:
  http-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-server
